Add new context keys of 4K builds to the keymap schema.
sublimelsp/LSP-json pull request #92
Opened 2021-05-29 11:47 UTC by Ultra-Instinct-05

This PR adds newly added context keys of the 4K build series to the keymap schema. 

Note: These aren't in the official documentation yet. There is an open issue for it https://github.com/sublimehq/sublime_text/issues/4063

Notes:
1. I haven't added `is_javadoc` because I don't know what it does as a context key. I have marked the description for it as a TODO in `PackageDev`. 

2. `panel_type` is a new one (not yet added to `PackageDev`), added in 4097. (Will do so in a future PR to it)

2021-05-29 18:18 UTC, rwols requested changes
I'm wondering where these context keys are described? I can't find them on docs.sublimetext.io nor on https://www.sublimetext.com/docs/key_bindings.html#context

EDIT: I guess the linked issue is enough proof :)

2021-05-30 04:26 UTC, Ultra-Instinct-05 commented on schemas/sublime-keymap.json
> +                  "The name of the currently focussed overlay",
Fixed. Sorry about these. Should probably turn on ST's spell checker.

2021-05-30 04:28 UTC, Ultra-Instinct-05 commented
> I'm wondering where these context keys are described? I can't find them on docs.sublimetext.io nor on https://www.sublimetext.com/docs/key_bindings.html#context

As I said, it's not yet in the official documentation. One has to go through the `Default/Default ($platform).sublime-keymap` to find these. As for the community docs, there is an open issue to add these https://github.com/sublimetext-io/docs.sublimetext.io/issues/39

2021-05-30 07:23 UTC, rwols approved these changes

2021-05-30 21:17 UTC, merged